name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  # CI build and test job
  build-and-test:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            g++-mingw-w64-i686 \
            g++-mingw-w64-x86-64 \
            clang \
            lld \
            pkg-config \
            zip \
            wine

      - name: Build Linux project
        run: |
          make build

      - name: Run Linux tests
        run: |
          make test

      - name: Build Windows x86 project
        run: |
          make windows-x86

      - name: Test Windows x86 project
        run: |
          make test-windows

      - name: Build Windows x64 project
        run: |
          make windows

      - name: Test Windows x64 project
        run: |
          make test-windows