name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Build job - run on release
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [linux-x86_64, windows-x86, windows-x86_64]
        include:
          - target: linux-x86_64
            setup: |
              sudo apt-get update
              sudo apt-get install -y build-essential clang lld pkg-config cmake ninja-build
          - target: windows-x86
            setup: |
              sudo apt-get update
              sudo apt-get install -y build-essential g++-mingw-w64-i686 pkg-config cmake ninja-build zip
          - target: windows-x86_64
            setup: |
              sudo apt-get update
              sudo apt-get install -y build-essential g++-mingw-w64-x86-64 pkg-config cmake ninja-build zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup CPM dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/CPM
            ~/AppData/Local/Temp/CPM
          key: cpm-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cpm-${{ runner.os }}-${{ matrix.target }}-

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: |
            build/**/CMakeCache.txt
            build/**/CMakeFiles/**
            build/**/cmake_install.cmake
          key: build-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/CMakeLists.txt', '**/src/**', '**/include/**', '**/cli/**') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.target }}-

      - name: Install build toolchain
        run: ${{ matrix.setup }}

      - name: Extract version
        run: |
          VERSION=$(cmake -P cmake/print_version.cmake)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Build version: $VERSION"

      - name: Configure and build binaries
        run: |
          case "${{ matrix.target }}" in
            linux-x86_64)
              cmake -B build/linux \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DBUILD_TESTS=OFF \
                    -DBUILD_DIAGNOSTIC=ON \
                    -DBUILD_SHARED_LIBS=OFF \
                    -G Ninja
              cmake --build build/linux --parallel $(nproc)
              BINARY_DIR="build/linux"
              ;;
            windows-x86)
              cmake -B build/windows-x86 \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_TOOLCHAIN_FILE="cmake/windows-x86-toolchain.cmake" \
                    -DBUILD_TESTS=OFF \
                    -DBUILD_DIAGNOSTIC=ON \
                    -DBUILD_SHARED_LIBS=OFF \
                    -G "MinGW Makefiles"
              cmake --build build/windows-x86 --parallel
              BINARY_DIR="build/windows-x86"
              ;;
            windows-x86_64)
              cmake -B build/windows-x64 \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_TOOLCHAIN_FILE="cmake/windows-toolchain.cmake" \
                    -DBUILD_TESTS=OFF \
                    -DBUILD_DIAGNOSTIC=ON \
                    -DBUILD_SHARED_LIBS=OFF \
                    -G "MinGW Makefiles"
              cmake --build build/windows-x64 --parallel
              BINARY_DIR="build/windows-x64"
              ;;
          esac
          
          echo "BINARY_DIR=$BINARY_DIR" >> $GITHUB_ENV

      - name: Verify binaries
        run: |
          case "${{ matrix.target }}" in
            linux-x86_64)
              file ${{ env.BINARY_DIR }}/bin/art2img | grep -q "ELF" && echo "Linux binary verified"
              file ${{ env.BINARY_DIR }}/bin/art2img_diagnostic | grep -q "ELF" && echo "Linux diagnostic verified"
              ;;
            *)
              file ${{ env.BINARY_DIR }}/bin/art2img.exe | grep -q "PE" && echo "Windows binary verified"
              file ${{ env.BINARY_DIR }}/bin/art2img_diagnostic.exe | grep -q "PE" && echo "Windows diagnostic verified"
              ;;
          esac

      - name: Create package
        run: |
          mkdir -p release/${{ matrix.target }}
          
          # Copy binaries
          case "${{ matrix.target }}" in
            linux-x86_64)
              cp ${{ env.BINARY_DIR }}/bin/art2img release/${{ matrix.target }}/art2img
              cp ${{ env.BINARY_DIR }}/bin/art2img_diagnostic release/${{ matrix.target }}/art2img_diagnostic
              BINARY_SUFFIX=""
              PACKAGE_EXT="tar.gz"
              ;;
            *)
              cp ${{ env.BINARY_DIR }}/bin/art2img.exe release/${{ matrix.target }}/art2img.exe
              cp ${{ env.BINARY_DIR }}/bin/art2img_diagnostic.exe release/${{ matrix.target }}/art2img_diagnostic.exe
              BINARY_SUFFIX=".exe"
              PACKAGE_EXT="zip"
              ;;
          esac
          
          # Copy documentation
          cp README.md release/${{ matrix.target }}/
          cp LICENSE release/${{ matrix.target }}/ 2>/dev/null || echo "No LICENSE file found"
          
          # Create platform-specific README
          cat > release/${{ matrix.target }}/README.txt << EOF
          art2img ${{ env.VERSION }} - ${{ matrix.target }}

          Multi-threaded ART to image converter for Duke Nukem 3D assets.

          Binaries:
          - art2img${BINARY_SUFFIX} - Main converter
          - art2img_diagnostic${BINARY_SUFFIX} - Diagnostic tool

          Quick Start:
          ${{ matrix.target == 'linux-x86_64' && './art2img' || 'art2img.exe' }} -f png -p PALETTE.DAT TILES000.ART

          See README.md for full documentation.
          EOF
          
          # Create archive
          if [[ "${{ matrix.target }}" == "linux-x86_64" ]]; then
            tar -czf art2img-${{ matrix.target }}-${{ env.VERSION }}.tar.gz -C release/${{ matrix.target }} .
          else
            cd release/${{ matrix.target }}
            zip -r ../../art2img-${{ matrix.target }}-${{ env.VERSION }}.zip .
            cd ../..
          fi
          
          echo "Package created: art2img-${{ matrix.target }}-${{ env.VERSION }}.${PACKAGE_EXT}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: art2img-${{ matrix.target }}
          path: |
            art2img-${{ matrix.target }}-*.${{ env.PACKAGE_EXT }}
          retention-days: 30

  # macOS build and release
  macos-build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup CPM dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/CPM
            ~/AppData/Local/Temp/CPM
          key: cpm-${{ runner.os }}-macos-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cpm-${{ runner.os }}-macos-

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: |
            build/**/CMakeCache.txt
            build/**/CMakeFiles/**
            build/**/cmake_install.cmake
          key: build-${{ runner.os }}-macos-${{ hashFiles('**/CMakeLists.txt', '**/src/**', '**/include/**', '**/cli/**') }}
          restore-keys: |
            build-${{ runner.os }}-macos-

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Configure CMake
        run: |
          cmake -B build/macos \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTS=OFF \
                -DBUILD_DIAGNOSTIC=ON \
                -DBUILD_SHARED_LIBS=OFF \
                -G Ninja

      - name: Build macOS binaries
        run: |
          cmake --build build/macos --parallel $(sysctl -n hw.ncpu)

      - name: Verify binaries
        run: |
          file build/macos/bin/art2img | grep -q "Mach-O" && echo "macOS binary verified"
          file build/macos/bin/art2img_diagnostic | grep -q "Mach-O" && echo "macOS diagnostic verified"

      - name: Create macOS package
        run: |
          VERSION=$(cmake -P cmake/print_version.cmake)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          mkdir -p release/macos-x86_64
          
          # Copy binaries
          cp build/macos/bin/art2img release/macos-x86_64/art2img
          cp build/macos/bin/art2img_diagnostic release/macos-x86_64/art2img_diagnostic
          
          # Copy documentation
          cp README.md release/macos-x86_64/
          cp LICENSE release/macos-x86_64/ 2>/dev/null || echo "No LICENSE file found"
          
          # Create platform-specific README
          cat > release/macos-x86_64/README.txt << EOF
          art2img $VERSION - macos-x86_64

          Multi-threaded ART to image converter for Duke Nukem 3D assets.

          Binaries:
          - art2img - Main converter
          - art2img_diagnostic - Diagnostic tool

          Quick Start:
          ./art2img -f png -p PALETTE.DAT TILES000.ART

          See README.md for full documentation.
          EOF
          
          # Create archive
          tar -czf art2img-macos-x86_64-$VERSION.tar.gz -C release/macos-x86_64 .
          
          echo "Package created: art2img-macos-x86_64-$VERSION.tar.gz"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: art2img-macos-x86_64
          path: |
            art2img-macos-x86_64-*.tar.gz
          retention-days: 30

  # Release job - run on release
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, macos-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Determine version
        run: |
          VERSION=$(cmake -P cmake/print_version.cmake)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          TAG_SOURCE="${GITHUB_REF_NAME:-${{ github.event.release.tag_name || '' }}}"
          if [ -z "$TAG_SOURCE" ]; then
            TAG_SOURCE="$VERSION"
          fi
          echo "TAG_NAME=$TAG_SOURCE" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          cat > release-notes.md << EOF
          # art2img ${{ env.TAG_NAME }}

          Multi-threaded ART to image converter for Duke Nukem 3D assets with support for multiple platforms and architectures.

          ## Downloads

          ### Linux
          - **x86_64**: \`art2img-linux-x86_64-*.tar.gz\`

          ### Windows
          - **x86**: \`art2img-windows-x86-*.zip\`
          - **x86_64**: \`art2img-windows-x86_64-*.zip\`

          ### macOS
          - **x86_64**: \`art2img-macos-x86_64-*.tar.gz\`

          ## Installation

          ### Linux
          \`\`\`bash
          tar -xzf art2img-linux-x86_64-*.tar.gz
          ./art2img --help
          \`\`\`

          ### Windows
          \`\`\`powershell
          Expand-Archive art2img-windows-x86_64-*.zip
          .\art2img.exe --help
          \`\`\`

          ### macOS
          \`\`\`bash
          tar -xzf art2img-macos-x86_64-*.tar.gz
          ./art2img --help
          \`\`\`

          ## Features
          - Multi-threaded extraction
          - PNG and TGA output with alpha channel support
          - Animation data extraction
          - Cross-platform compatibility
          - Static binaries (no dependencies required)

          ## Verification
          All binaries are statically linked and digitally verified. No additional dependencies required.

          ---
          [Full Documentation](https://github.com/raulcorreia7/art2img)
          EOF

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}